### PR TITLE
RSpec test

### PR DESCRIPTION
**Pull request by ShoiraTa**
# Testing  Ruby Code - Enumerable

- Added specs for all “Enumerables” methods we previously created.
- Wrote test  for all custom enumerable methods
- Used one “it” block for each expected behavior
- Wrote test cases positive and negative scenarios.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @ShoiraTa and @Stephanie041996 
Such a remarkable project you made :+1: ! Awesome README :100: !, Positive and Negative Scenarios :tada:
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] I enjoyed with test cases, we need  to write test cases for the `multiply_els` method.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_enumerables.png) from [Odin](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/testing-your-ruby-code)) 
- [x] Please Update the description of **Run tests**  in the README file. You can add the run commands here. 

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by ShoiraTa** [comment]
Hello,
Thank you for your comments, we have worked on all the above mentioned changes
thank you

**Comment by umairarshadbutt** [comment]
Hi @ShoiraTa 
Great Job. You can resubmit for review.

Best,
Umair Arshad

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @ShoiraTa  &  @Stephanie041996

Good job on implementing the suggested changes
**You may close this Pull Request and merge the changes**
  
**Keep being awesome devs and good luck with your next milestone!**


Cheers and Happy coding!👏👏👏

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

**Pull request merged**
